version: '3.3'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - './db:/data/db'

  frontend:
    image: node:14.8
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run build:watch"
    depends_on:
      - backend
    volumes:
      - ./:/usr/src/app

  backend:
    image: node:14.8
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
    restart: always
    environment:
      MONGODB_URL: mongodb://mongo:27017/dds
      OPENFISCA_URL: https://openfisca.mes-aides.org/
    ports:
      - '8080:8080'
      - '9001:9001'
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - ./:/usr/src/app

volumes:
  node_modules:
